name: Setup and Install deps
description: Setup Node.js/pnpm. Install dependencies.
inputs:
  node-version:
    default: lts/*
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Install deps
      run: pnpm install
      shell: bash
    - name: Setup ni
      run: npm i -g @antfu/ni
      shell: bash
